"""Repository over SQLite (stdlib sqlite3, JSON columns for nested contracts).

W2 implements. Tables (see docs/CONTRACTS.md): properties, opportunities, opportunity_events,
inbound_messages, source_documents, evidence_observations, underwriting_runs, policy_versions,
skeptic_reports, outbound_drafts, notifications.
"""

from __future__ import annotations

import os
from pathlib import Path

from dealsieve.schemas import (
    DashboardStats,
    Evidence,
    InboundMessage,
    Notification,
    Opportunity,
    OpportunityDetail,
    OpportunityEvent,
    OpportunityStatus,
    OutboundDraft,
    Property,
    SkepticReport,
    UnderwritingResult,
    WatchlistItem,
)

DEFAULT_DB_PATH = Path(os.environ.get("DEALSIEVE_DB_PATH", "data/dealsieve.db"))


class Repo:
    """All methods are synchronous. One Repo per process is fine; sqlite3 with WAL."""

    def __init__(self, db_path: str | os.PathLike[str] | None = None) -> None:
        self.db_path = Path(db_path) if db_path else DEFAULT_DB_PATH
        raise NotImplementedError("W2: dealsieve.persistence.repo.Repo")

    def init_schema(self) -> None: ...

    # messages
    def store_inbound_message(self, message: InboundMessage) -> None: ...
    def message_exists(self, message_id: str) -> bool: ...
    def get_message(self, message_id: str) -> InboundMessage | None: ...

    # properties & opportunities
    def upsert_property(self, prop: Property) -> Property: ...
    def get_property(self, property_id: str) -> Property | None: ...
    def list_properties(self) -> list[Property]: ...
    def create_opportunity(self, opp: Opportunity) -> Opportunity:
        """Assigns deal_number (sequential) and persists."""
        ...
    def get_opportunity(self, opportunity_id: str) -> Opportunity | None: ...
    def get_opportunity_by_deal_number(self, deal_number: int) -> Opportunity | None: ...
    def save_opportunity(self, opp: Opportunity) -> Opportunity:
        """Update derived state only (status, working_values, viability, latest_run_id, ...)."""
        ...
    def list_opportunities(self, status: OpportunityStatus | None = None) -> list[Opportunity]: ...

    # events (append-only)
    def append_event(self, event: OpportunityEvent) -> OpportunityEvent:
        """Assigns seq (per opportunity, monotonically increasing) and persists. Returns the stored event."""
        ...
    def list_events(self, opportunity_id: str) -> list[OpportunityEvent]: ...

    # evidence & documents
    def store_evidence(self, opportunity_id: str, evidence: list[Evidence]) -> None: ...
    def list_evidence(self, opportunity_id: str) -> list[Evidence]: ...
    def store_document(self, opportunity_id: str, message_id: str, filename: str, sha256: str, text: str | None) -> None: ...

    # underwriting runs (append-only)
    def store_underwriting_run(self, run: UnderwritingResult) -> None: ...
    def get_underwriting_run(self, run_id: str) -> UnderwritingResult | None: ...
    def list_underwriting_runs(self, opportunity_id: str) -> list[UnderwritingResult]: ...
    def record_policy_version(self, policy_version: str, name: str, raw_yaml: str) -> None: ...

    # skeptic, drafts, notifications
    def store_skeptic_report(self, report: SkepticReport) -> None: ...
    def list_skeptic_reports(self, opportunity_id: str) -> list[SkepticReport]: ...
    def store_draft(self, draft: OutboundDraft) -> None: ...
    def get_draft(self, draft_id: str) -> OutboundDraft | None: ...
    def update_draft(self, draft: OutboundDraft) -> None: ...
    def list_drafts(self, status: str | None = None, opportunity_id: str | None = None) -> list[OutboundDraft]: ...
    def store_notification(self, notification: Notification) -> None: ...
    def list_notifications(self, opportunity_id: str | None = None) -> list[Notification]: ...

    # read models for API/dashboard
    def dashboard_stats(self, policy_version: str) -> DashboardStats: ...
    def watchlist(self) -> list[WatchlistItem]:
        """All non-DEAD opportunities sorted by distance_pct ascending (REVIEW first, then NEAR, WATCH)."""
        ...
    def opportunity_detail(self, opportunity_id: str) -> OpportunityDetail | None: ...
